---

- name: Install DSS
  become: true
  become_user: "{{dss_service_user}}"
  command: "{{dss_install_dir_location}}/dataiku-dss-{{dss_version}}/installer.sh -t deployer -d {{dss_data_dir_location}} -p {{dss_port}}" -l "{{licence_file_path}}"
  args:
    creates: "{{dss_data_dir_location}}/dss-version.json"
  tags: [dss]

- name: Download kubectl
  get_url:
    url: "https://dl.k8s.io/release/{{kubectl_version}}/bin/linux/amd64/kubectl"
    dest: "/usr/bin/kubectl"
    owner: root
    group: root
    mode: 0755
  become: true

- name: Download eksctl
  get_url:
    url:  "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_linux_amd64.tar.gz"
    dest: "/tmp/eksctl.tar.gz"

- name: Unarchive eksctl
  become: true
  unarchive:
    src: "/tmp/eksctl.tar.gz"
    dest: "/usr/bin"
    creates: "/usr/bin/eksctl"
    remote_src: yes
  tags: [setup, dss-setup]