---
dss_service_user: dataiku
dss_service_user_home: /home/dataiku
package_tmp_dir: /var/tmp
dss_install_dir_location: /data
dss_data_dir_location: /data/dataiku
dss_node_poll_fqdn: true # If true, use ansible_fqdn else use ansible_host
dataiku_download_url: "https://downloads.dataiku.com/public/studio/"

# The DSS licence is required at build time for some node types
license_region: eu-west-2
license_source: parameter-store
#license_source: secrets-manager
#license_source: hashicorp-vault
license_backend_path: /dss/licence
license_file_path: /tmp/licence
vault_endpoint: "http://172.0.0.1:8200/"
vault_token: "vault-plaintext-root-token"