---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    dss_version: "12.4.2" #https://doc.dataiku.com/dss/latest/release_notes/12.html#version-12-4-0-december-6th-2023
    dss_api_version: "12.5.0" #https://pypi.org/project/dataiku-api-client/
    spark_plugin_version: "3.4.1" #https://downloads.dataiku.com/public/dss/12.4.0/

    jdbc_download_tgz_url: "https://go.microsoft.com/fwlink/?linkid=2262683"
    jdbc_package_tmp_dir: "/var/tmp/tarballs"
    jdbc_tarball_name: "jdbc.tar.gz"
    jdbc_src_filename: "sqljdbc_12.6/enu/jars/mssql-jdbc-12.6.1.jre8.jar"
    jdbc_dest_dir: "{{dss_jdbc_dir_location}}"
    jdbc_dest_filename: "{{mssql-jdbc-12.6.1.jre8.jar}}"

    dss_port: 11200
    kubectl_version: "v1.20.10"
    dss_node_type: design
    is_jmx_enabled: true
    collect_default_metrics_enabled: true
    enable_r: true
    enable_r4: false
    install_with_license: false
  roles:
    - role: dataiku-dss
